### ISSUE TITLE
assets base_path parameter not considered by encore_entry_link_tags and encore_entry_script_tags functions

### ISSUE THREAD

**Issue by barbuslex** [symfony/webpack-encore-bundle#222]
Hi,

I have this config in a template bundle : 
`webpack.config.js`
```js
Encore
    .setOutputPath('./src/Resources/public/')
    .setPublicPath('')
    .setManifestKeyPrefix('')

    .addEntry('coloradmin', './assets/coloradmin.js')
    .disableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(false)
    .enableVersioning(true)

    .configureBabel((config) => {
        config.plugins.push('@babel/plugin-proposal-class-properties');
    })
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = 3;
    })
    .enableSassLoader()
    .autoProvideVariables()
    .addPlugin(new CopyPlugin({
        patterns: [
            { from: "assets/img/", to: "images" },
        ]
    }))

    .addLoader({
        test: require.resolve('pace-js'),
        use: [{
            loader: 'imports-loader',
            options: {
                additionalCode: 'var define = false;'
            }
        }]
    });
    
;

module.exports = Encore.getWebpackConfig();
module.exports.output.publicPath = '';
```

`webpack_encore.yaml`
```yaml
parameters: 
  color_admin.builds_path: '%kernel.project_dir%/public/bundles/coloradmin'
  color_admin.json_manifest_path: '%kernel.project_dir%/public/bundles/coloradmin/manifest.json'

webpack_encore:
  builds:
    coloradmin: '%color_admin.builds_path%'

framework:
  assets:
    packages:
      coloradmin:
          base_path: '%env(WEBPACK_PUBLIC_PATH)%bundles/coloradmin/'
          json_manifest_path: '%color_admin.json_manifest_path%'
```

When i use `{{ asset('coloradmin.css', 'coloradmin') }}` the path generated is `/bundles/coloradmin/coloradmin.464b2fc0.css`.
When i use `{{ encore_entry_link_tags('coloradmin.css', null, 'coloradmin')` the path generated is `/coloradmin.464b2fc0.css`.

Same with scripts tags/functions.

Have you a workaround for considering base_path parameter with webpack encore functions ? (i need to use env variable from parent root project (inexist env in bundle)).

Thanks
