### ISSUE TITLE
Optional default entrypoint when using multiple entrypoints

### ISSUE THREAD

**Issue by emodric** [symfony/webpack-encore-bundle#32]
I'm trying out multiple entrypoints, and first test was to define a single `builds` directive:

```
webpack_encore:
    builds:
        frontend: '%kernel.project_dir%/web/build'
```

However, Webpack Encore complains that the `output_path` is not configured: `The child node "output_path" at path "webpack_encore" must be configured.`. Is this the intended behaviour? How would I go about specifying this kind of config as a starting point for other developers on my team to extend with more entrypoints?

**Comment by steven-pribilinskiy** [comment]
I see some confusion in what param stands for the "build package"
By following the example in README an error is thrown and it looks like the `builds` option from `config.yml` is ignored
```
{{ encore_entry_script_tags('entry1', 'frontend') }}
```

While if I put it as 3rd parameter it works correctly
```
{{ encore_entry_script_tags('entry1', null, 'frontend') }}
```

[A template in a test fixture](https://github.com/symfony/webpack-encore-bundle/blob/master/tests/fixtures/template.twig) helped me to figure this out

**Comment by steven-pribilinskiy** [comment]
By looking at the [source code](https://github.com/symfony/webpack-encore-bundle/blob/9c89795a4577c522101206a1a88272660735257c/src/Twig/EntryFilesTwigExtension.php#L49) it's even more confusing
What's the difference between `$entryName` and `$entrypointName` and now what `$packageName` stands for?

**Comment by steven-pribilinskiy** [comment]
Btw, for `output_path` I put an empty string and it works fine:
```
webpack_encore:
    output_path: ''
    builds:
        backend: '%kernel.root_dir%/../../web/build/backend'
        backend-design-tools: '%kernel.root_dir%/../../web/build/backend-design-tools'
        frontend: '%kernel.root_dir%/../../web/build/frontend'
```
Then everywhere I use the package name as 3rd argument
